#!/bin/bash

# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

# This hook copies the kernel image(s) used in the integration tests from /tmp.

REPO_PATH="${BUILDKITE_BUILD_CHECKOUT_PATH}"
RESDIR="resources/kernel"
WORKDIR="/tmp/vmlinux_busybox"
KERNEL="linux-4.14.176"
VMLINUX=vmlinux-hello-busybox-halt

arch=$(dpkg --print-architecture)
if [ "$arch" == "amd64" ]; then
    cp "$WORKDIR/$KERNEL/$VMLINUX" "$RESDIR"
fi
